apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: atmosphere-v2-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: weather-app
  minReplicaCount: 0     
  maxReplicaCount: 15
  pollingInterval: 5
  cooldownPeriod: 60      
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: atmosphere-bus-kafka.default.svc.cluster.local:9092
      consumerGroup: atmosphere-v2-group
      topic: scaling-signals
      lagThreshold: '1'
    metricType: Value
