apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: weather-predictor-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: weather-app
  minReplicaCount: 2
  maxReplicaCount: 15
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: 10.96.62.205:9092
      consumerGroup: atmosphere-group
      topic: scaling-signals
      lagThreshold: '1'
