apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictor-engine
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predictor # This MUST match the template labels below
  template:
    metadata:
      labels:
        app: predictor
    spec:
      containers:
      - name: predictor
        image: predictor-llm:v4 
        imagePullPolicy: IfNotPresent
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: KAFKA_BROKER
<<<<<<< HEAD
          value: "atmosphere-bus-kafka:9092"
        livenessProbe:
          exec:
            command:
            - pgrep
            - python
          initialDelaySeconds: 10
          periodSeconds: 5
=======
          value: "atmosphere-bus-kafka.default.svc.cluster.local:9092"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-credentials
              key: OPENAI_API_KEY
>>>>>>> 4a7d044 (updated app to provide AI driven analysis)
